config/routes.rb
Rails.application.routes.draw do 

  Blacklight.add_routes(self)
  
  root :to => "catalog#index"
  match 'catalog/:id/image', :to => 'catalog#image', :as => 'image' 
  match 'catalog/:id/brief_availability', :to => 'catalog#brief_availability', :as => 'brief_availability'
  match 'catalog/:id/availability', :to => 'catalog#availability', :as => 'availability'
  match 'catalog/:id/status', :to => 'catalog#availability', :as => 'status'
  match 'catalog/:id/image_load', :to => 'catalog#image_load', :as => 'image_load'
  match 'catalog/:id/firehose', :to => 'catalog#firehose', :as => 'firehose', :defaults => { :format => 'xml'}
  match 'catalog/:id/view', :to => 'catalog#page_turner', :as => 'view'
  match 'catalog/:id/page_turner', :to => 'catalog#page_turner', :as => 'page_turner'
  match 'fedora_metadata/:id/:pid.:format', :to => 'catalog#fedora_metadata', :as => 'fedora_metadata'
  match 'folder/refworks_texts', :to => 'folder#refworks_texts', :as => 'refworks_texts'
  match 'folder/article_destroy', :to => 'folder#article_destroy', :as => 'folder_article_destroy'
  match 'folder/csv', :to => 'folder#csv', :as => 'csv'
  match 'folder/citation', :to => 'folder#citation', :as => 'citation'
  match 'folder/email', :to => 'folder#email', :as => 'email'
  match 'folder/endnote', :to => 'folder#endnote', :as => 'endnote' 
  match 'reserves/email', :to => 'reserves#email', :as => 'reserves_email'
  match 'advanced', :to => 'advanced#index', :as => 'advanced'
  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'logged_out', :to => 'user_sessions#logged_out', :as => 'logged_out'
  match 'patron_login', :to => 'user_sessions#patron_login', :as => 'patron_login'
  match 'do_patron_login', :to => 'user_sessions#do_patron_login', :as => 'do_patron_login'
  match 'account_requests/:id/renew/:checkout_key', :to => 'account_requests#renew', :as => 'renew'
  match 'account_requests/renew_all', :to => 'account_requests#renew_all', :as => 'renew_all'
  match 'special_collections_requests/:id/new', :to => 'special_collections_requests#new', :as => 'new_special_collections_request'
  
  match "music/facet/:id", :to => 'music#facet', :as => 'music_facet'
  resources :music, :only => [:index, :show, :update]
  
  match "video/facet/:id", :to => 'video#facet', :as => 'video_facet'
  resources :video, :only => [:index, :show, :update]

  resources :account, :only => [:index] do
    member do
      get :not_found
    end
    collection do
      get :checkouts
      get :holds
      get :reserves
      get :notices
      get :renew
      get :review
      get :select
    end
  end

  resources :maps
  resources :maps_users
  resources :call_number_ranges

  resources :special_collections_requests, :except => [:new] do
    member do
      get :start
      get :non_uva
      get :show
    end
  end

  resources :articles, :only => [:index] do
    collection do
      get :facet
      get :advanced
    end
  end

  resources :account_requests, :only => [] do
    member do
      get :start_hold
      post :create_hold
    end
  end

  resources :folder, :only => [:index, :create, :update, :destroy] do
    collection do
      delete :clear
    end
  end
  
end

app/models/special_collections_request.rb
class SpecialCollectionsRequest < ActiveRecord::Base
  has_many :special_collections_request_items, :dependent => :destroy 
  validates_presence_of :user_id
  before_update :set_processed_at 
  
  attr_accessor :document
  
  # locations and call numbers are submitted via a web form as a hash keyed by location
  # example:  
  # { "SC-STKS"=>{"X030761746"=>["PS3623 .R539 S48 2010"]}, 
  #   "SC-BARR-X"=>{"X004958786"=>["MSS 6251 -- 6251-bn"], "X004958758"=>["MSS 6251 -- 6251-bn Box 2"]} }
  # build these out into request items and add those items to this request object
  def build(locations_with_call_numbers)
    return if locations_with_call_numbers.nil? or locations_with_call_numbers.empty?
    locations_with_call_numbers.each { |location, barcode_set|
      barcode_set.each do |barcode, call_numbers|
        call_numbers.each do |call_number|
          item = SpecialCollectionsRequestItem.new(:location => location, :call_number => call_number, :barcode => barcode)
          self.special_collections_request_items << item
        end
      end
    }
  end
  
  private
    def set_processed_at
      self.processed_at = Time.now
    end
  
end

app/controllers/special_collections_requests_controller.rb
# special collections requests are for patrons in special collections to make requests for
# viewing items.  Also used by special collections administrators to view and process the
# request queue.
require 'uva/ldap'
require '/usr/local/projects/virgo/lib/uva/solr_helper_override'
class SpecialCollectionsRequestsController < ApplicationController
  include Blacklight::SolrHelper
  include UVA::SolrHelperOverride

  before_filter :verify_admin, :except => [:new, :create, :start, :non_uva]
  before_filter :bypass_login, :only => [:start]
  before_filter :setup_request, :only => [:start, :non_uva, :new]
  before_filter :build_request, :only => [:create]
  before_filter :verify_user, :only => [:new, :create]
  
  # dummy method to display which type of login a person wants to use (UVa or non-UVa)
  def start
  end

  # allows a non-uva person to enter his or her library id
  def non_uva
  end

  # pulls up the items and allows a person to construct a request
  def new
    response, document = get_solr_response_for_doc_id(params[:id], params)
    document.availability = Firehose::Availability.find(document)
    @special_collections_request.document = document
  end
  
  # submits the request
  def create
    if @special_collections_request.special_collections_request_items.empty?
      flash[:error] = 'You must select at least one item.'
      redirect_to new_special_collections_request_path(:id => @special_collections_request.document_id)
      return
    end
    respond_to do |format|
      if @special_collections_request.save
        session[:non_uva_login] = nil
        flash[:notice] = 'Request successfully submitted.'
        format.html { redirect_to(catalog_path(@special_collections_request[:document_id])) }
      else
        format.html { render :action => 'start' }
      end
    end
  end
  
  # used by special collections staff to view the queue  
  def index
    start_time = DateTime.civil(params[:range][:"date(1i)"].to_i,params[:range][:"date(2i)"].to_i,params[:range][:"date(3i)"].to_i) rescue DateTime.civil(Time.now.year, Time.now.month, Time.now.day)
    end_time = start_time + 1
    @date = start_time.strftime("%m/%d/%Y")
    @special_collections_requests = SpecialCollectionsRequest.find(:all, :conditions => {:created_at => start_time..end_time}, :order => 'created_at desc') || []
    @special_collections_requests.each do |request|
      response, document = get_solr_response_for_doc_id(request.document_id, params)
      request.document = document    
    end
  end
  
  # used by special collections staff to review an individual request
  def edit
    @special_collections_request = SpecialCollectionsRequest.find(params[:id])
    response, document = get_solr_response_for_doc_id(@special_collections_request.document_id)
    document.availability = Firehose::Availability.find(document)
    @special_collections_request.document = document   
  end
  
  # used by special collections staff to process the request
  def update
    @special_collections_request = SpecialCollectionsRequest.find(params[:id])  
    respond_to do |format|
      if @special_collections_request.update_attributes(params[:special_collections_request])
        format.html { redirect_to :action => 'show', :format => 'pdf' }      
      else
        format.html { render :action => 'edit' }
      end
    end
  end
  
  # generates a pdf of the request
  def show
    @special_collections_request = SpecialCollectionsRequest.find(
      params[:id], :include => :special_collections_request_items, 
      :order => 'special_collections_request_items.location, special_collections_request_items.barcode')
    @response, @document = get_solr_response_for_doc_id(@special_collections_request.document_id) 
    @date = @special_collections_request.created_at.strftime("%A, %B %e, %Y")
    respond_to do |format|
      format.pdf do
        prawnto :prawn => { :page_layout => :landscape }
        format.pdf { prawnto :filename => "Request #{params[:id]}", :inline => false }
      end
    end
  end  
  
  protected
  # verifies that the current user is a special collections administrator
  def verify_admin
    if current_user.nil?
      flash[:error] = "Please log in to manage Special Collections Requests. <a class='btn small' href='/login?redirect=special_collections_admin'>Login</a>".html_safe
      redirect_to catalog_index_path 
    else
      unless SpecialCollectionsUser.find_by_computing_id(current_user[:login])
        flash[:error] = "You are not authorized to manage Special Collections Requests."
        redirect_to catalog_index_path 
      end
    end
  end
  
  # makes it so that a person doesn't have to re-login if they are already logged in
  def bypass_login
    return if current_user.nil? || current_user[:login].nil?
    redirect_to new_special_collections_request_path(:id => params[:id])
  end
  
  # generates a new Special Collections Request based on the id in the params
  def setup_request
    @special_collections_request = SpecialCollectionsRequest.new
    @special_collections_request.document_id = params[:id]
  end
  
  # builds out a request from the params
  def build_request
    @special_collections_request = SpecialCollectionsRequest.new(params[:special_collections_request])
    @special_collections_request.build(params[:location_plus_call_number])
  end
  
  # ensures that there is a user id present
  # if the non-uva login route was specified, verifies that the supplied id is not a computing id
  # does a patron lookup to ensure that it's a valid patron id
  def verify_user
    # if we came from a non-uva login id, set that in session
    if !current_user.nil?
      @special_collections_request.user_id = current_user[:login]
    else
      session[:non_uva_login] = params[:user_id] unless params[:user_id].blank?
      @special_collections_request.user_id = session[:non_uva_login]
      uva_id?
    end
    check_login
    patron_lookup
  end
  
  # makes sure that a user id is present
  def check_login
    if @special_collections_request.user_id.blank?
      flash[:error] = 'You must establish your identify before making a request.' 
      redirect_to start_special_collections_request_path(:id => @special_collections_request.document_id)
    end
  end
  
  # looks up the user id to see if it's a UVa computing id
  def uva_id?
    return false if @special_collections_request.user_id.blank?
    @special_collections_request.extend(UVA::Ldap)
    unless @special_collections_request.full_name.blank?
      flash[:error] = 'UVa members should use NetBadge to authenticate'
      session[:non_uva_login] = nil
      redirect_to start_special_collections_request_path(:id => @special_collections_request.document_id)
    end
  end
  
  # looks up the user id to see if it's a valid patron.  
  # sets the name from the patron record.
  def patron_lookup
    return if @special_collections_request.user_id.blank?
    patron = get_patron(@special_collections_request.user_id)
    last_name = patron.last_name rescue ""
    first_name = patron.first_name rescue ""
    middle_name = patron.middle_name rescue ""
    unless last_name.blank?
      name = ("" + last_name + ", " + first_name + " " + middle_name).strip
    else
      name = patron.display_name rescue ""
    end
    if @special_collections_request.user_id =~ /^demo_/
      @special_collections_request.name = @special_collections_request.user_id
    elsif name.blank?
      flash[:error] = 'Unable to locate your patron record.  Please verify your login information and try again.'
      session[:non_uva_login] = nil
      redirect_to catalog_path(:id => @special_collections_request.document_id)
    else
      @special_collections_request.name = name
    end
  end
end

app/views/special_collections_requests/_user_form.html.erb
<div>
<% if one_copy?(@special_collections_request.document.availability) %>
	Call number of requested item:
<% else %>
	There are multiple copies of this item. Please consult the item record for description of differences, where applicable, and use the checkboxes to select the copy or copies you wish to receive. 
<% end %>
</div>
<% @special_collections_request.document.availability.special_collections_holdings.each do |holding| %>
	<% holding.copies.each do |copy| %>
		<% barcode = copy.barcode %>
		<% home_location = copy.home_location %>
		<% current_location = copy.current_location %>
		<% call_number = holding.call_number %>
		<% if !copy.available? %>
		  <%= check_box_tag "location_plus_call_number[#{home_location.code}][#{barcode}]", call_number, item_included?(@special_collections_request, home_location.code, call_number, barcode)%>
       <%= home_location.code %>, <%= call_number %><br />
       <% next%>
     <% end %>
    <% if one_copy?(@special_collections_request.document.availability) %>
      <%= hidden_field_tag("location_plus_call_number[#{current_location.code}][#{barcode}][]", call_number) -%>
    <% else %>
      <%= check_box_tag "location_plus_call_number[#{current_location.code}][#{barcode}][]", call_number,  item_included?(@special_collections_request, current_location.code, call_number, barcode) -%>
    <% end %>
    <%= current_location.code %>, <%= call_number %><br />    
 <% end %>
<% end %>

<p>
  <%= label(:special_collections_request, :user_note, 'Indicate box number, folder, volume number, etc. (if applicable)') %>
  <%= user_form.text_field :user_note, :size => 55 %>
</p>
<p>
  <%= user_form.hidden_field :document_id %>
</p>

<p>
  <% if current_user and SpecialCollectionsRequestsInternalUser.find_by_computing_id(current_user[:login])%>
    <%= user_form.check_box :internal, :checked=>true %> This is an internal request
  <% end %>
</p>

app/views/special_collections_requests/edit.html.erb
<div id="list_heading"><h1>Request for <%= @special_collections_request.document.value_for :title_display %></h1></div>

<div class="tool_content spec_coll">
	
<% if @special_collections_request.errors.any? %>
  <ul>
    <% @special_collections_request.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<div id="returnToItem">
<%= link_to '&larr; Return to request list'.html_safe, special_collections_requests_path %>
</div>

<%= form_for(@special_collections_request) do |f| -%>
<fieldset>
  <%= render :partial => 'user_form', :object => f %>
  <p>
  <%= label(:special_collections_request, :staff_note, 'Staff Notes') %>
  <%= f.text_area :staff_note %>
  </p>
  <%= f.submit "Generate PDF", :class => 'button' %> or 
  <%= link_to 'Return to request list', special_collections_requests_path %>
</fieldset>

<ul>
  <% @special_collections_request.document.marc_display.location_notes.each do |loc| -%>
    <li><%= loc %></li>
  <% end -%>
</ul>

<% end -%>

</div>

app/views/special_collections_requests/index.html.erb
<% @add_to_html_head = capture do %>
  <meta http-equiv="refresh" content="60" > 
<% end %>

<div id="list_heading"><h1>Special Collections Requests</h1></div>

<div class="tool_content spec_coll">
	
<div class="dateSelector">
<%= form_tag(special_collections_requests_path, :method => :get) do %>
  Select a date: <%= date_select('range', 'date', :order => [:month, :day, :year])%>
  <%= submit_tag "Go" %>
<% end %>
</div>

<h3>Requests for <%= @date %></h3>
<div class="requests-legend">
  <span class="processed-label">Processed</span>
  <span class="unprocessed-label">Unprocessed</span>
  <span class="internal-label">Unprocessed (internal)</span>
</div>
<table id="special_collections_requests">
<tr>
  <th>Request ID</th>
  <th>User ID</th>
  <th>Name</th>
  <th>Item</th>
  <th>Requested</th>
  <th>Processed</th>
  <th>View Request</th>
</tr>
<% for request in @special_collections_requests -%>
  <% if !request.processed_at.nil? %>
  	<tr class="processed">
  <% elsif request.internal? %>
  	<tr class="unprocessed_internal">
  <% elsif !request.internal? %>
  	<tr class="unprocessed">
  <% end %>
    <td><%= h request.id %></td>
    <td><%= h request.user_id %></td>
    <td><%=  h request.name %></td>
    <td>
    <%= request.document.value_for(:title_display)%><br />
    <%= request.document.value_for(:author_display)%>
    </td>
    <td><%= request.created_at.strftime("%I:%M%p")%></td>
    <td><%= request.processed_at.strftime("%I:%M%p") rescue '&nbsp;'.html_safe %></td>	
    <td><%= link_to("View", edit_special_collections_request_path(request.id))%></td>
  </tr>  
<% end -%>
</table>

</div>

app/views/special_collections_requests/new.html.erb
<div id="list_heading"><h1>Request for <%= @special_collections_request.document.value_for :title_display %></h1></div>

<div class="tool_content spec_coll">
	
<% if @special_collections_request.errors.any? %>
  <ul>
    <% @special_collections_request.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div id="returnToItem">
<%= link_to "&larr; Return to item record".html_safe, catalog_path(params[:id]) %>
</div>

<%= form_for(@special_collections_request) do |f| -%>
<div id="special_collections_content">
<fieldset>
  <%= render :partial => 'user_form', :object => f %>
  <%= f.submit "Request", :class => 'button' %> or 
  <%= link_to 'cancel', catalog_path(params[:id]) %>
</fieldset>
</div>
<% end -%>
</div>

app/views/special_collections_requests/non_uva.html.erb
<div id="tool_heading"><h1>Special Collections Requests</h1></div>

<div class="tool_content spec_coll">
<%= form_tag(new_special_collections_request_path, :method => :get) do -%>
<fieldset>
<p>
  <%= label_tag 'user_id', 'Enter your Library ID'%>
  <%= text_field_tag 'user_id' %>
</p>
<p>
  <%= hidden_field_tag 'id', @special_collections_request.document_id %>
</p>
  <%= submit_tag "Request", :class => 'button' %> or 
  <%= link_to 'cancel', catalog_path(params[:id]) %>
</fieldset>
<% end -%>
</div>

app/views/special_collections_requests/start.html.erb
<div id="tool_heading"><h1>Special Collections Requests</h1></div>

<div class="tool_content spec_coll">

<%= link_to 'UVa login', login_path(:id => @special_collections_request[:document_id], :redirect => 'special_collections_user')%> | <%= link_to 'Non-UVa login', non_uva_special_collections_request_path(:id => @special_collections_request[:document_id])%>

</div>