config/routes.rb
Rails.application.routes.draw do 

  Blacklight.add_routes(self)
  
  root :to => "catalog#index"
  match 'catalog/:id/image', :to => 'catalog#image', :as => 'image' 
  match 'catalog/:id/brief_availability', :to => 'catalog#brief_availability', :as => 'brief_availability'
  match 'catalog/:id/availability', :to => 'catalog#availability', :as => 'availability'
  match 'catalog/:id/status', :to => 'catalog#availability', :as => 'status'
  match 'catalog/:id/image_load', :to => 'catalog#image_load', :as => 'image_load'
  match 'catalog/:id/firehose', :to => 'catalog#firehose', :as => 'firehose', :defaults => { :format => 'xml'}
  match 'catalog/:id/view', :to => 'catalog#page_turner', :as => 'view'
  match 'catalog/:id/page_turner', :to => 'catalog#page_turner', :as => 'page_turner'
  match 'fedora_metadata/:id/:pid.:format', :to => 'catalog#fedora_metadata', :as => 'fedora_metadata'
  match 'folder/refworks_texts', :to => 'folder#refworks_texts', :as => 'refworks_texts'
  match 'folder/article_destroy', :to => 'folder#article_destroy', :as => 'folder_article_destroy'
  match 'folder/csv', :to => 'folder#csv', :as => 'csv'
  match 'folder/citation', :to => 'folder#citation', :as => 'citation'
  match 'folder/email', :to => 'folder#email', :as => 'email'
  match 'folder/endnote', :to => 'folder#endnote', :as => 'endnote' 
  match 'reserves/email', :to => 'reserves#email', :as => 'reserves_email'
  match 'advanced', :to => 'advanced#index', :as => 'advanced'
  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'logged_out', :to => 'user_sessions#logged_out', :as => 'logged_out'
  match 'patron_login', :to => 'user_sessions#patron_login', :as => 'patron_login'
  match 'do_patron_login', :to => 'user_sessions#do_patron_login', :as => 'do_patron_login'
  match 'account_requests/:id/renew/:checkout_key', :to => 'account_requests#renew', :as => 'renew'
  match 'account_requests/renew_all', :to => 'account_requests#renew_all', :as => 'renew_all'
  match 'special_collections_requests/:id/new', :to => 'special_collections_requests#new', :as => 'new_special_collections_request'
  
  match "music/facet/:id", :to => 'music#facet', :as => 'music_facet'
  resources :music, :only => [:index, :show, :update]
  
  match "video/facet/:id", :to => 'video#facet', :as => 'video_facet'
  resources :video, :only => [:index, :show, :update]

  resources :account, :only => [:index] do
    member do
      get :not_found
    end
    collection do
      get :checkouts
      get :holds
      get :reserves
      get :notices
      get :renew
      get :review
      get :select
    end
  end

  resources :maps
  resources :maps_users
  resources :call_number_ranges

  resources :special_collections_requests, :except => [:new] do
    member do
      get :start
      get :non_uva
      get :show
    end
  end

  resources :articles, :only => [:index] do
    collection do
      get :facet
      get :advanced
    end
  end

  resources :account_requests, :only => [] do
    member do
      get :start_hold
      post :create_hold
    end
  end

  resources :folder, :only => [:index, :create, :update, :destroy] do
    collection do
      delete :clear
    end
  end
  
end

app/models/maps_user.rb
# A person who is allowed to administer maps
class MapsUser < ActiveRecord::Base

end

app/controllers/maps_users_controller.rb
# Maps users is for maintaining the list of people who are allowed to administer maps.
class MapsUsersController < ApplicationController
  
  before_filter :verify_map_user
  
  # list the map users
  def index
    @maps_users = MapsUser.find(:all)
  end
  
  # start a new map user
  def new
    @maps_user = MapsUser.new
  end
  
  # create a new map user
  def create
    @maps_user = MapsUser.new(params[:maps_user])
    respond_to do |format|
      if @maps_user.save
        flash[:notice] = 'Maps user succesfully created'
        format.html { redirect_to(maps_users_path) }
      else
        format.html { render :action => 'new' }
      end
    end
  end
  
  # delete a map user
  def destroy
     @maps_user = MapsUser.find(params[:id])
     @maps_user.destroy
     respond_to do |format|
       format.html { redirect_to(maps_users_url) }
     end
   end

end

app/views/maps_users/index.html.erb
<div id="list_heading"><h1>Maps Users</h1></div>

<div class="tool_content">

  <%= link_to '&larr; Return to maps'.html_safe, maps_path, :class => 'maps-return' %>

  <div class="maps-container">
    <h2>Existing Users <%= link_to 'Add a new map user', new_maps_user_path, :class => 'btn' %></h2>
    <ul class="user-list">
    <% for maps_user in @maps_users -%>
      <li><%= maps_user.computing_id %> <%= button_to "Delete", maps_user_url(maps_user), :method => :delete, :confirm => 'Are you sure you want to delete this map user? You cannot undo this.', :class => 'btn small' %></li>
    <% end %>
    </ul>
  </div>

</div>

app/views/maps_users/new.html.erb
<div id="list_heading"><h1>Create a New Map User</h1></div>

<div class="tool_content">

<% if @maps_user.errors.any? %>
  <ul>
    <% @maps_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
	
<%= form_for(@maps_user) do |f| -%>
<fieldset class="maps-user-form maps-container">
<div class="row">
  <%= label(:maps_user, :computing_id, "Computing ID") %>
  <%= f.text_field :computing_id %>
</div>
<div class="row">
  <%= f.submit "Create", :class => 'button btn' %>
  <%= link_to 'Cancel', maps_users_path, :class => 'btn' %>
  </div>
</fieldset>
<% end -%>

</div>