config/routes.rb
Rails.application.routes.draw do 

  Blacklight.add_routes(self)
  
  root :to => "catalog#index"
  match 'catalog/:id/image', :to => 'catalog#image', :as => 'image' 
  match 'catalog/:id/brief_availability', :to => 'catalog#brief_availability', :as => 'brief_availability'
  match 'catalog/:id/availability', :to => 'catalog#availability', :as => 'availability'
  match 'catalog/:id/status', :to => 'catalog#availability', :as => 'status'
  match 'catalog/:id/image_load', :to => 'catalog#image_load', :as => 'image_load'
  match 'catalog/:id/firehose', :to => 'catalog#firehose', :as => 'firehose', :defaults => { :format => 'xml'}
  match 'catalog/:id/view', :to => 'catalog#page_turner', :as => 'view'
  match 'catalog/:id/page_turner', :to => 'catalog#page_turner', :as => 'page_turner'
  match 'fedora_metadata/:id/:pid.:format', :to => 'catalog#fedora_metadata', :as => 'fedora_metadata'
  match 'folder/refworks_texts', :to => 'folder#refworks_texts', :as => 'refworks_texts'
  match 'folder/article_destroy', :to => 'folder#article_destroy', :as => 'folder_article_destroy'
  match 'folder/csv', :to => 'folder#csv', :as => 'csv'
  match 'folder/citation', :to => 'folder#citation', :as => 'citation'
  match 'folder/email', :to => 'folder#email', :as => 'email'
  match 'folder/endnote', :to => 'folder#endnote', :as => 'endnote' 
  match 'reserves/email', :to => 'reserves#email', :as => 'reserves_email'
  match 'advanced', :to => 'advanced#index', :as => 'advanced'
  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'logged_out', :to => 'user_sessions#logged_out', :as => 'logged_out'
  match 'patron_login', :to => 'user_sessions#patron_login', :as => 'patron_login'
  match 'do_patron_login', :to => 'user_sessions#do_patron_login', :as => 'do_patron_login'
  match 'account_requests/:id/renew/:checkout_key', :to => 'account_requests#renew', :as => 'renew'
  match 'account_requests/renew_all', :to => 'account_requests#renew_all', :as => 'renew_all'
  match 'special_collections_requests/:id/new', :to => 'special_collections_requests#new', :as => 'new_special_collections_request'
  
  match "music/facet/:id", :to => 'music#facet', :as => 'music_facet'
  resources :music, :only => [:index, :show, :update]
  
  match "video/facet/:id", :to => 'video#facet', :as => 'video_facet'
  resources :video, :only => [:index, :show, :update]

  resources :account, :only => [:index] do
    member do
      get :not_found
    end
    collection do
      get :checkouts
      get :holds
      get :reserves
      get :notices
      get :renew
      get :review
      get :select
    end
  end

  resources :maps
  resources :maps_users
  resources :call_number_ranges

  resources :special_collections_requests, :except => [:new] do
    member do
      get :start
      get :non_uva
      get :show
    end
  end

  resources :articles, :only => [:index] do
    collection do
      get :facet
      get :advanced
    end
  end

  resources :account_requests, :only => [] do
    member do
      get :start_hold
      post :create_hold
    end
  end

  resources :folder, :only => [:index, :create, :update, :destroy] do
    collection do
      delete :clear
    end
  end
  
end

app/models/map.rb
# A map is a description and URL of a map that can be associated with a map guide
class Map < ActiveRecord::Base
  has_many :call_number_ranges, :dependent => :destroy, :order => :call_number_range
  
  belongs_to :library
  validates_presence_of :url, :description, :library_id
  
  def self.find_best_map(holding, copy)
    ranges = CallNumberRange.location_and_call_number_match(holding, copy)
    return ranges[0].map unless ranges.empty?
    # whole library match
    hits = Map.all(:joins => 'INNER JOIN libraries on maps.library_id = libraries.id LEFT JOIN call_number_ranges on call_number_ranges.map_id = maps.id', 
                    :conditions => ["libraries.name = ? AND call_number_range IS NULL", holding.library.code])
    return hits[0] unless hits.empty?
  end
end

app/controllers/maps_controller.rb
# A map is just a description and URL for a map.
# Maps controller is only used by map administrators for creating map guides.
class MapsController < ApplicationController
  
  before_filter :verify_map_user
  
  # list all of the maps
  def index
    @maps = Map.joins(:library).order('name, description')
  end
  
  # start a new map
  def new
    @map = Map.new
  end
  
  # create a map
  def create
    @map = Map.new(params[:map])
    respond_to do |format|
      if @map.save
        flash[:notice] = 'Map succesfully created'
        format.html { redirect_to(maps_path) }
      else
        format.html { render :action => 'new' }
      end
    end
  end
  
  # edit a map
  def edit
    @map = Map.find(params[:id])
  end    
  
  # update a map
  def update
    @map = Map.find(params[:id])
    respond_to do |format|
      if @map.update_attributes(params[:map])
        flash[:notice] = 'Map was successfully updated'
        format.html { redirect_to(maps_path) }
      else
        format.html { render :action => 'edit' }
      end
    end
  end
  
  # delete a map
  def destroy
    @map = Map.find(params[:id])
    @map.destroy
    respond_to do |format|
      format.html { redirect_to(maps_url) }
    end
  end
end

app/views/maps/_form.html.erb
<div class="row">
  <%= label(:map, :library_id) %>
  <%= collection_select(:map, :library_id, Library.find(:all, :order => :name), :id, :name, options = {:prompt => "Select a library"}) %>
</div>

<div class="row">
  <%= label(:map, :description) %>
  <%= form.text_field :description %>
</div>

<div class="row">
  <%= label(:map, :url) %>
  <%= form.text_field :url %>
</div>

app/views/maps/edit.html.erb
<div id="list_heading"><h1>Edit Map</h1></div>

<div class="tool_content">

<% if @map.errors.any? %>
  <ul>
    <% @map.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@map) do |f| %>
<fieldset class="maps-form maps-container">
  <%= render :partial => 'form', :object => f %>
  <div class="row">
	  <%= f.submit "Update", :class => 'button btn primary' %>
  <%= link_to 'Cancel', maps_path, :class => 'btn' %>
  </div>
</fieldset>
<% end %>

</div>

app/views/maps/index.html.erb
<% @add_to_html_head = capture do %>
  <%= javascript_include_tag 'maps.js' %>
<% end %>

<div id="list_heading"><h1>Maps</h1></div>

<div class="tool_content">

<div class="maps-container">
  <h3 class="maps-button-heading">Administration:</h3> <%= link_to 'Add a New Map', new_map_path, :class => 'btn' %><%= link_to 'Edit Maps Users', maps_users_path, :class => 'btn' %>
</div>

<div class="expand-contract">
  <span class="expand-contract-label">Toggle Libraries:</span>
  <button class="btn small">Show All</button>
</div>

<% libraries = Library.find(:all, :order => :name) -%>
<% libraries.each do |library| -%>
  <% if library.maps.length > 0 -%>
    <div id="library-<%= library.id %>" class="library-map-container">
      <h1 class="library-name"><%= library.name.capitalize %> (<%= library.maps.length%>) <span class="toggle-library-maps">Show</span></h1>
      <% library.maps.each do |map| -%>
        <div id="map_<%= map.id %>" class="maps-container map-listing">
          <div class="map-entry">
      	    <h2 class="map-name"><%= h map.library.name %>: <%= h map.description %> <a class="map-url" href="<%= h map.url %>">Map Image</a></h2>
            <div class="map-tools"><%= button_to 'Edit', edit_map_path(map.id), :class => 'btn', :method => :get %><%= button_to "Delete", map_url(map), :method => :delete, :confirm => 'Are you sure you want to delete this map and its call numbers? This action cannot be undone.', :class => 'btn' %></div>
          </div>
    
        	<div class="map-guides">    
          <% unless map.call_number_ranges.empty? %>
            <h3>Call Number Ranges</h3>
            <% map.call_number_ranges.each do |range| %>
              <div class="range-listing <%= cycle 'odd', 'even' %>">
                <span><%= h range.location %>&nbsp;&nbsp;&mdash;&nbsp;&nbsp;<%= h range.call_number_range %></span>
                <span class="range-remove"><%= button_to "remove", call_number_range_path(range.id), :method => :delete, :confirm => 'Are you sure you want to delete this entry?', :class => 'btn small' %></span>
              </div>
            <% end %>
          <% end %>
    
          <h3>Add a Call Number Range <span class="optional">optional</span></h3>
      		<%= form_tag(call_number_ranges_path) do %>
      		  <%= label_tag 'location', 'Location' %>
      			<%= select_tag :location, options_for_select(Location.find(:all, :order=>:value).collect{ |c| [c.value, c.value]}.insert(0, ""))   %>
      			<%= label_tag 'call_number_range', 'Range' %>
      			<%= text_field_tag(:call_number_range) %>
      			<%= hidden_field_tag(:map_id, map.id) %>
      			<%= submit_tag "Add", :class => "btn small" %>
      		<% end %>
      		</div>
        </div>
      <% end -%>
    </div>
  <% end -%>
<% end -%>
</div>

app/views/maps/new.html.erb
<div id="list_heading"><h1>Create a New Map</h1></div>

<div class="tool_content">

<% if @map.errors.any? %>
  <ul>
    <% @map.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
	
<%= form_for(@map) do |f| -%>
<fieldset class="maps-form maps-container">
  <%= render :partial => 'form', :object => f %>
    <div class="row">
		<%= f.submit "Create", :class => 'button btn primary' %>
    <%= link_to 'Cancel', maps_path, :class => 'btn' %>
    </div>
</fieldset>
<% end -%>

</div>