config/routes.rb
Rails.application.routes.draw do 

  Blacklight.add_routes(self)
  
  root :to => "catalog#index"
  match 'catalog/:id/image', :to => 'catalog#image', :as => 'image' 
  match 'catalog/:id/brief_availability', :to => 'catalog#brief_availability', :as => 'brief_availability'
  match 'catalog/:id/availability', :to => 'catalog#availability', :as => 'availability'
  match 'catalog/:id/status', :to => 'catalog#availability', :as => 'status'
  match 'catalog/:id/image_load', :to => 'catalog#image_load', :as => 'image_load'
  match 'catalog/:id/firehose', :to => 'catalog#firehose', :as => 'firehose', :defaults => { :format => 'xml'}
  match 'catalog/:id/view', :to => 'catalog#page_turner', :as => 'view'
  match 'catalog/:id/page_turner', :to => 'catalog#page_turner', :as => 'page_turner'
  match 'fedora_metadata/:id/:pid.:format', :to => 'catalog#fedora_metadata', :as => 'fedora_metadata'
  match 'folder/refworks_texts', :to => 'folder#refworks_texts', :as => 'refworks_texts'
  match 'folder/article_destroy', :to => 'folder#article_destroy', :as => 'folder_article_destroy'
  match 'folder/csv', :to => 'folder#csv', :as => 'csv'
  match 'folder/citation', :to => 'folder#citation', :as => 'citation'
  match 'folder/email', :to => 'folder#email', :as => 'email'
  match 'folder/endnote', :to => 'folder#endnote', :as => 'endnote' 
  match 'reserves/email', :to => 'reserves#email', :as => 'reserves_email'
  match 'advanced', :to => 'advanced#index', :as => 'advanced'
  match 'login', :to => 'user_sessions#new', :as => 'login'
  match 'logout', :to => 'user_sessions#destroy', :as => 'logout'
  match 'logged_out', :to => 'user_sessions#logged_out', :as => 'logged_out'
  match 'patron_login', :to => 'user_sessions#patron_login', :as => 'patron_login'
  match 'do_patron_login', :to => 'user_sessions#do_patron_login', :as => 'do_patron_login'
  match 'account_requests/:id/renew/:checkout_key', :to => 'account_requests#renew', :as => 'renew'
  match 'account_requests/renew_all', :to => 'account_requests#renew_all', :as => 'renew_all'
  match 'special_collections_requests/:id/new', :to => 'special_collections_requests#new', :as => 'new_special_collections_request'
  
  match "music/facet/:id", :to => 'music#facet', :as => 'music_facet'
  resources :music, :only => [:index, :show, :update]
  
  match "video/facet/:id", :to => 'video#facet', :as => 'video_facet'
  resources :video, :only => [:index, :show, :update]

  resources :account, :only => [:index] do
    member do
      get :not_found
    end
    collection do
      get :checkouts
      get :holds
      get :reserves
      get :notices
      get :renew
      get :review
      get :select
    end
  end

  resources :maps
  resources :maps_users
  resources :call_number_ranges

  resources :special_collections_requests, :except => [:new] do
    member do
      get :start
      get :non_uva
      get :show
    end
  end

  resources :articles, :only => [:index] do
    collection do
      get :facet
      get :advanced
    end
  end

  resources :account_requests, :only => [] do
    member do
      get :start_hold
      post :create_hold
    end
  end

  resources :folder, :only => [:index, :create, :update, :destroy] do
    collection do
      delete :clear
    end
  end
  
end

app/controllers/catalog_controller.rb
# Catalog controller base class is included in the Blacklight plugin.  Overriding all sorts of methods for
# custom behavior.  Once folder logic is included in the plugin, we can remove several methods.
require '/usr/local/projects/virgo/lib/uva/fedora'
require '/usr/local/projects/virgo/lib/firehose/holds'
require '/usr/local/projects/virgo/lib/firehose/availability'
require '/usr/local/projects/virgo/lib/uva/advanced_search/controller'
require '/usr/local/projects/virgo/lib/uva/advanced_search/advanced_search_fields'
require '/usr/local/projects/virgo/lib/uva/articles_helper'
require '/usr/local/projects/virgo/lib/uva/solr_helper_override'
class CatalogController < ApplicationController
  include UVA::Fedora
  include Blacklight::Catalog
  include Firehose::Holds
  include UVA::AdvancedSearch::Controller
  include UVA::AdvancedSearch::AdvancedSearchFields
  include UVA::ArticlesHelper
  include UVA::SolrHelperOverride
  include BlacklightAdvancedSearch::ParseBasicQ
  
  # the featured_documents are used when there are no queries or filters applied
  before_filter :notices_update, :only=>[:index, :show]
  before_filter :adjust_for_advanced_search, :only=>:index
  before_filter :adjust_for_portal, :only=>:index
  before_filter :setup_call_number_search, :only=>:index
  before_filter :adjust_for_special_collections_search, :only=>:index
  before_filter :adjust_for_full_view, :only=>[:index, :show]
  before_filter :resolve_sort, :only=>:index
  before_filter :add_lean_query_type, :only=>[:image_load, :image, :brief_availability]
  before_filter :recaptcha_check, :only=>:send_email_record
  before_filter :articles, :only=>[:email, :send_email_record, :citation]
  before_filter :set_solr_document, :only=>[:availability, :brief_availability, :firehose, :image_load, :image, :page_turner, :fedora_metadata]
  before_filter :set_document_availability, :only=>[:availability, :brief_availability]
  
  # when a request for /catalog/HIDDEN_SOLR_ID is made, this method is executed...
  rescue_from HiddenSolrID, :with => lambda {
    flash[:notice] = "Sorry, you seem to have encountered an error."
    redirect_to catalog_index_path and return
  }

  # when a path is requested that should result in a redirect, this method is executed  
  rescue_from UVA::RedirectNeeded do |redirect| 
    redirect_to redirect.message and return
  end
  
  # too many of these are showing up in ExceptionNotification emails, ususally generated
  # by a bot crawling the site.  This is here to keep the email volume lower.
  rescue_from ActionController::InvalidAuthenticityToken, :with => lambda {
    redirect_to catalog_index_path and return
  }
  
  # When RSolr::RequestError is raised, this block is executed.
  # The index action will more than likely throw this one.
  # Example, when the standard query parser is used, and a user submits a "bad" query.
  rescue_from RSolr::Error::InvalidRubyResponse do |error|
    # when solr (RSolr) throws an error, this method is executed.
    flash[:notice] = "Sorry, I don't understand your search."
    notify_about_exception(error)
    redirect_to catalog_index_path and return
  end
  
  # some googlebot keeps doing an OPTIONS request on status, and status doesn't allow that.
  # trying to reduce exception emails
  rescue_from ActionController::MethodNotAllowed, :with => lambda {
    redirect_to catalog_index_path and return
  }
    
  configure_blacklight do |config|
    config.default_solr_params = {
      :qt => "search",
      :rows => 20
    }
    config.default_qt = "search"
    # solr field values given special treatment in the index (search results) view
    config.index.show_link = "title_display"
    config.index.record_display_type = "format"
    
    # solr field values given special treatment in the show (single result) view
    config.show.html_title = "title_display"
    config.show.heading = "title_display"
    config.show.display_type = "format"
    
    # facets
    config.add_facet_field 'library_facet', :label => 'Library' 
    config.add_facet_field 'format_facet', :label => 'Format'
    config.add_facet_field 'published_date_facet', :label => 'Publication Era'
    config.add_facet_field 'author_facet', :label => 'Author'
    config.add_facet_field 'subject_facet', :label => 'Subject'
    config.add_facet_field 'language_facet', :label => 'Language'
    config.add_facet_field 'call_number_facet', :label => 'Call Number'
    config.add_facet_field 'region_facet', :label => 'Geographic Location'
    config.add_facet_field 'digital_collection_facet', :label => 'Digital Collection'
    config.add_facet_field 'source_facet', :label => 'Source'
    config.add_facet_field 'series_title_facet', :label => 'Series'
    config.add_facet_field 'call_number_broad_facet', :label => 'Call Number'
    
    # index fields
    config.add_index_field 'title_display', :label => 'Title:' 
    config.add_index_field 'author_display', :label => 'Author:' 
    config.add_index_field 'format_facet', :label => 'Format:' 
    config.add_index_field 'language_facet', :label => 'Language:' 
    config.add_index_field 'published_date_display', :label => 'Published:' 
    config.add_index_field 'location_facet', :label => 'Location:' 
  
    # show fields
    config.add_show_field 'year_facet', :label => 'Date:'
    config.add_show_field 'author_display', :label => 'Creator:'
    config.add_show_field 'digital_collection_facet', :label => 'Collection:'
    config.add_show_field 'media_resource_id_display', :label => 'Type:'
    config.add_show_field 'title_display', :label => 'Title:' 
    config.add_show_field 'subtitle_display', :label => 'Subtitle:' 
    config.add_show_field 'format_facet', :label => 'Format:'
    config.add_show_field 'language_facet', :label => 'Language:'
    config.add_show_field 'note_display', :label => 'Note:'
    config.add_show_field 'published_date_display', :label => 'Published:'
    config.add_show_field 'isbn_display', :label => 'ISBN'

    # search fields
    config.add_search_field('author') do |field|
      field.solr_local_parameters = {
       :qf => '$qf_author',
       :pf => '$pf_author'
      }
    end
    config.add_search_field('title') do |field|
      field.solr_local_parameters = {
       :qf => '$qf_title',
       :pf => '$pf_title'
      }
    end
    config.add_search_field('journal') do |field|
      field.label = 'Journal Title'
      field.solr_local_parameters = {
       :qf => '$qf_journal_title',
       :pf => '$pf_journal_title'
      }
    end
    config.add_search_field('subject') do |field|
      field.solr_local_parameters = {
       :qf => '$qf_subject',
       :pf => '$pf_subject'
      }
    end
    config.add_search_field 'keyword' do |field|
      field.label = 'Keywords'
      field.solr_local_parameters = {
        :qf => '$qf_keyword',
        :pf => '$pf_keyword'
       }
    end
    config.add_search_field('call_number') do |field|
      field.label = 'Call Number'
      field.solr_local_parameters = {
       :qf => '$qf_call_number',
       :pf => '$pf_call_number'
      }
    end
    config.add_search_field('published') do |field|
      field.label = 'Publisher/Place of Publication'
      field.solr_local_parameters = {
       :qf => '$qf_published',
       :pf => '$pf_published'
      }
    end
    config.add_search_field('publication_date') do |field|
      field.label = 'Year Published'
      field.range = 'true'
      field.solr_field = 'year_multisort_i'
    end
    config.add_search_field('issn') do |field|
      field.include_in_advanced_search = false
      field.label = 'ISSN'
      field.solr_local_parameters = {
        :qf => '$qf_issn',
        :pf => '$pf_issn'
      }
    end
    config.add_search_field('isbn') do |field|
      field.include_in_advanced_search = false
      field.label = 'ISBN'
      field.solr_local_parameters = {
        :qf => '$qf_isbn',
        :pf => '$pf_isbn'
      }
    end
    
    # sort fields
    config.add_sort_field 'score desc, year_multisort_i desc', :label => 'Relevancy', :sort_key => 'relevancy'
    config.add_sort_field 'date_received_facet desc', :label => 'Date Received', :sort_key => 'received'
    config.add_sort_field 'year_multisort_i desc', :label => 'Date Published - newest first', :sort_key => 'published'
    config.add_sort_field 'year_multisort_i asc', :label => 'Date Published - oldest first', :sort_key => 'published_a'
    config.add_sort_field 'title_sort_facet asc, author_sort_facet asc', :label => 'Title', :sort_key => 'title'
    config.add_sort_field 'author_sort_facet asc, title_sort_facet asc', :label => 'Author', :sort_key => 'author'
    
    config.spell_max = 5

    # advanced search facets
    config.advanced_search = {
      :form_solr_parameters => {
        'facet.field' => ['library_facet', 'format_facet', 'call_number_broad_facet', 'digital_collection_facet'],
        'facet.limit' => -1, # return all facet values
        'facet.sort' => 'index', # sort by byte order of values
      },
      :url_key => 'advanced',
      :qt => 'search'
    }
  end
  
  # get search results from the solr index
  # overriding from plugin to add cleanup_call_number_search and json response
  def index
    (@response, @document_list) = get_search_results(params)
    cleanup_call_number_search
    respond_to do |format|
      format.html { render :layout => index_layout }
      format.json { render :json => @response.to_json}
      format.rss  { render :layout => false }
    end
  end
  
  # displays values and pagination links for a single facet field
  # overriding from plugin to add json response
  def facet
    @pagination = get_facet_pagination(params[:id], params)
    respond_to do |format|
       format.html {render :layout => "popup"}
       format.json {render :json => @pagination.to_json}
     end
  end

  # get item availability status
  def availability
    respond_to do |format|
      format.html
      format.json {render :layout=>false}
    end
  end
  

app/views/catalog/_analytics.html.erb
<!-- Piwik --> 
<script type="text/javascript">
var pkBaseURL = (("https:" == document.location.protocol) ? "https://analytics.lib.virginia.edu/" : "http://analytics.lib.virginia.edu/");
document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));
</script><script type="text/javascript">
try {
var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1);
piwikTracker.trackPageView();
piwikTracker.enableLinkTracking();
} catch( err ) {}
</script><noscript><p><img src="http://analytics.lib.virginia.edu/piwik.php?idsite=1" style="border:0" alt="" /></p></noscript>
<!-- End Piwik -->

app/views/catalog/_availability.erb
<% # make sure document.availability was returned from the availability service -%>
<% if document.availability -%>
<% document.availability.summary_libraries.each do |library| -%>
<%= library.name %>
<% library.summary_locations.each do |location| -%>
<%= location.name %>
<% location.summaries.each do |summary| -%>
<%= summary.text %>, <%= summary.note %>
<% end -%>
<% end -%>
<% end -%>
<% if document.availability.holdings.size == 0 -%>
No information available for this item.
<% else -%>
<% document.availability.holdings.each do |holding| -%>
<% holding.copies.each do |copy| -%>

Library: <%= holding.library.name %>
<% if !holding.library.is_sas? -%>
Location: <%= location_text(holding, copy) %>
Availability: <%= availability_text(copy) %>
Call Number: <%= holding.call_number %>
<% else %>	
Location: <%= location_text(holding, copy) %>
Call Number: <%= sas_call_number_text(holding, copy) %>
<% end -%>

<% end -%>
<% end -%>
<% end -%>

<% end -%>

app/views/catalog/_colorbox.html.erb
<%# Include ColorBox-related files only once on the page -%>
<% unless @colorbox_loaded -%>
  <%= stylesheet_link_tag javascript_path('colorbox/uva/colorbox.css') %>
  <%= stylesheet_link_tag 'uva_colorbox.css' %>
  <%= javascript_include_tag 'colorbox/colorbox/jquery.colorbox.min.js' %>
  <% @colorbox_loaded = true -%>
<% end -%>

<%# Set up a ColorBox group (group of <a> elements with same @rel value)
  # containing only the images associated with this particular record -%>
<script type="text/javascript">
$(document).ready(function(){
  $(".imageCollection a").colorbox({maxHeight: "100%", photo:true,maxWidth:"95%",scalePhotos:true,opacity:0.7,current:"{current} of {total}"});
});
</script>

app/views/catalog/_document_actions.html.erb
<div id="ActionListContainer">
	<ul class="action_list">
		<li class="list_title">Starred Items</li>
		<li class="list_body">
			<ul class="action_list_menu all_star_menu">
				<li class="all_action"><a class="view_star_list" href="/folder">View Starred Items</a></li>
				<li class="all_action"><%= link_to "Clear Starred Items", clear_folder_path, :class => 'clear_all' %></li>
			</ul>
			<ul class="action_list_menu">
				<li class="add_action"><%= link_to "Cite", citation_path %></li>
				<li class="add_action"><%= link_to "Email", email_path %></li>
				<li><a href="/folder?view=print" target="_blank">Print</a></li>
				<li class="refworks_action"><%= link_to "Export (Refworks)", refworks_texts_path %>
				</li>
				<li class="add_action"><%= link_to "Export (EndNote/Zotero)", endnote_path %></li>
				<li class="add_action"><%= link_to "Place on Course Reserve", reserves_email_path %></li>
			</ul>
		</li>
	</ul>
</div>

app/views/catalog/_document_list.html.erb
<div id="results">
  <h1 class="visuallyhidden">Search Results</h1>
  <% if video_portal? and (params[:catalog_select] == "catalog" or params[:catalog_select].nil?) %>
    <div class="document video_doc video_head_row">
      <div class="video_head tools"><!-- number and star --></div>
      <div class="video_head title">Title</div>
      <div class="video_head format">Format</div>
      <div class="video_head year">Year</div>
      <div class="video_head availability">Location &amp; Availability</div>
      <div class="video_head callNumberField">Call #</div>
    </div>
  <% end %>
	<% @document_list.each_with_index do |document,counter| %>
	 <%= render_document_partial document, :index, counter, @response.params[:start].to_i %>
	<% end %>
</div>

app/views/catalog/_folder_control.html.erb
<% if item_in_folder?(document.value_for(:id)) %>
  <div class="folder_container"><%= link_to 'Remove Star', folder_path(document[:id]), :class=>'deleteFolder_link', :title=>'Remove Star' %></div>
<% elsif item_in_article_folder?(document.id) %>
	<div class="folder_container"><%= link_to 'Remove Star', folder_article_destroy_path(:article_id => document[:id]), :class=>'deleteFolderArticle_link', :title=>'Remove Star' 	%></div>
<% else %>
  <%= render :partial=>'catalog/folder_form', :locals=>{:document=>document} %>
<% end %>

app/views/catalog/_folder_form.html.erb
<div class="folder_container">
<%= form_tag("/folder", :name => "folder#{document[:id]}", :class => 'addFolderForm') do -%>
	<% if document.doc_type == :article %>
		<%= hidden_field_tag(:article_id, h(document.id), :id => "id#{document.id}") %>
  <% else %>
		<%= hidden_field_tag(:id, h(document[:id]), :id => "id#{document[:id]}") %>
	<% end %>
  <%= link_to('Add Star', folder_index_path, :class => 'submitForm', :title=>'Add to Starred Items')%>
  <%= submit_tag 'Add Star', :id => "submitFolderForm_#{document[:id]}", :class => 'hide' %>
<% end %>
</div>

app/views/catalog/_holdings.html.erb
<table class="holdings">
	<thead>
		<tr class="head_row">
			<th class="holding_head library_name">Library</th>
			<th class="holding_head location_name">Location</th>
			<th class="holding_head map_it">Map</th>
			<th class="holding_head num_available">Availability</th>
			<th class="holding_head call_number">Call Number</th>
		</tr>		
	</thead>
	<tbody>
		
	<% if !@document.availability or @document.availability.holdings.size == 0 %>
		<tr class="holding first even">
			<td class="holding_data no_info" colspan="5">No information available for this item.</td>
		</tr>
	<% else %>

		<% i = 0 %>

		<% special_collections_lens? ? holdings = document.availability.special_collections_holdings : holdings = document.availability.holdings %>

	  <% holdings.each do |holding| %>
        
	    <% holding.copies.each do |copy| %>
    
	        <tr class="holding<%= ' first' if (i == 0) %> <%= cycle(" even", " odd") -%>">
    
	        <td class="holding_data library_name"><%= holding.library.name %></td>
    
	    		<% if !holding.library.is_sas? %>

	    				<td class="holding_data location_name">
	    					<%= location_text(holding, copy) %>
	    				</td>
				
	    				<td class="holding_data map_it">
	    					<%= link_to_map(holding, copy) %>
	            </td>

	    				<td class="holding_data availability">
	    					<%= "<span class='availability-indicator #{availability_text(copy).downcase}'>#{availability_text(copy)}</span>".html_safe %>
	    					<%= '<span class="availability-indicator non-circ">Non-Circ.</span>'.html_safe if !copy.circulates? %>
	    				</td>

	    				<td class="holding_data call_number">
	    					<%= holding.call_number %>
	    				</td>

	  			<% else %>
			
	  				<td class="holding_data section_name">
	  					<%= location_text(holding, copy) %>
	  				</td>		

	    			<td class="holding_data map">
	  					<%= link_to_map(holding, copy) %>
	          </td>

	  				<td class="holding_data availability">
	  				</td>

	      	  <td class="holding_data call_number">
	  					<%= sas_call_number_text(holding, copy) %>
	  				</td>
				
	  			<% end %>
  			
	  			</tr>
  			
	  			<% i += 1 %>
  			
	  		<% end %>	         
  	  
	  <% end %> 

	<% end %>
		
	</tbody>
</table> <!-- end table.holdings -->

app/views/catalog/_marc_view.html.erb
<h1>Librarian View</h1>
<div id="marc_view">
  <% fields = @document.to_marc.find_all{|f| ('000'..'999') === f.tag }  %>
  <div class="field">LEADER <%= @document.to_marc.leader %></div>
  <%- fields.each do |field| -%>
	<%- unless field.tag.to_s == "940" or field.tag.to_s == "946" -%>
	  <div class="field">
	  	<div class="tag_ind">
	      <span class="tag">
	        <%= h field.tag %>
	  	  </span>
		  <%- if field.is_a?(MARC::ControlField) -%>
		    <span class="control_field_values">
		      <%= h field.value %>
		    </span>
		  <%- else -%>
		    <div class="ind1">
		      <%= !field.indicator1.blank? ? h(field.indicator1) : "&nbsp;&nbsp;".html_safe -%>
		    </div>
		    <div class="ind2">
		      <%= !field.indicator2.blank? ? h(field.indicator2) : "&nbsp;&nbsp;".html_safe -%>
		    </div>
		  </div>
		  <div class="subfields">
		    <%- field.each do |sub| -%>
			  <span class="sub_code"><%= h sub.code %>|</span> <%= h sub.value %>
			<%- end -%>
		  <%- end -%>
	    </div>
	  </div>
	<%- end-%>
  <%- end -%>
</div>

app/views/catalog/_search_elsewhere.html.erb
<aside class="search-elsewhere grid_24 alpha omega">
  <h1 class="elsewhere-heading">Looking for different results?</h1>
  <ul class="elsewhere-links">
    <%= search_elsewhere_links %>
  </ul>
  <h2 class="elsewhere-heading">Elsewhere</h2>
  <ul class="elsewhere-links">
    <li><a href="http://guides.lib.virginia.edu/az">Databases</a></li>
    <li><a href="http://guides.lib.virginia.edu/journalfinder">Journal Finder</a></li>
    <li><a href="http://research.lib.virginia.edu/">Subject Guides</a></li>
  </ul>
</aside>

app/views/catalog/_show_tools.html.erb
<div class="add_star">
	  <div class="folder_form">
	    <%= render :partial=>'folder_control', :locals=>{:document=>@document} %>
	  </div>
</div>

<div id="ActionListContainer" role="complementary">	
	<ul class="action_list">
		<li class="list_title">Item Actions</li>
		<li class="list_body">
			<ul class="action_list_menu all_star_menu">
				<li class="all_action"><a class="view_star_list" href="/folder">View Starred Items</a></li>
			</ul>
			<ul class="action_list_menu">
				<% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
  				<li class="Z3988-container"><%= zotero_span(@document) %></li>
				<% end %>
				
				<% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
					<li class="cite_this">
						<%= link_to "Cite", citation_catalog_path(:id => @document.id), {:id => 'citation'} %>
    			</li>
  			<% end %>

		    <li class="email_this">
		       <%= link_to "Email", email_catalog_path(:id => @document.id), {:id => 'email'} %>
		    </li>
		
		    <li class="sms_this">
		       <%= link_to "Text Message", sms_catalog_path(:id => @document.id), {:id => 'sms'} %>
		    </li>

			  <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
			    <li class="refworks">
			      <%= link_to "Export (RefWorks)", refworks_export_url(@document[:id]), :target => '_blank' %> 
			    </li>
			  <% end %>
  
			  <% if @document.export_formats.keys.include?( :endnote ) %>
			     <li class="endnote">
			       <%= link_to "Export (EndNote/Zotero)", catalog_path(@document[:id], :format => 'endnote') %>
			     </li>
			  <% end %>

    		<li class="delicious"><%= link_to 'Export (Delicious)', delicious_export_url(@document), :target=>:_blank %></li>
			
			<li>
		       <%= link_to "Place on Course Reserve", reserves_email_path(:id => @document.id), {:id => 'reserves_email'} %>
		    </li>

			</ul>
		</li>
	</ul>
</div>

app/views/catalog/_sort_and_per_page.html.erb
<% total = @response.response['numFound'] %>
<% if total > 0 and @response.docs.size > 0 %>
  <div id="searchTools" class="tools box clearFix">
  
    <div id="SortFormContainer">
  	  <% unless total < 2 %>
  	  <% if params[:controller] == 'folder' %>
  	    <% link = folder_index_path %>
  	  <% elsif params[:controller] == 'articles' %>
  	    <% link = articles_path %>
  	  <% else %>
  	    <% link = portal_index_path %>
  	  <% end %>
				<%= form_tag link, :method => :get, :class => 'sort', :id => 'sort_form' do %>
					<%= label_tag(:sort_key) do %>
						Sort by <%= select_tag(:sort_key, options_for_select(sort_fields, h(params[:sort_key])), :onchange => 'this.form.submit()') %>
					<% end %>
      		<%= search_as_hidden_fields(:omit_keys => [:page, :sort_key]) %>			
  	      <noscript><%= submit_tag 'sort results' %></noscript>
  			<% end %>
  		<% end %>
  	</div>
  
    <div id="PerPageContainer">
      <% unless total < 1 %>
        <% if params[:controller] == 'folder' %>
          <% link = folder_index_path %>
        <% elsif params[:controller] == 'articles' %>
          <% link = articles_path %>
        <% else %>
          <% link = portal_index_path %>
        <% end %>
    		<%= form_tag link, :method=>:get, :class=>'per_page' do %>
    			<%= label_tag(:per_page) do %>
						Show <%= select_tag(:per_page, options_for_select(['20', '50', '100'], h(params[:per_page])), :title => "Number of results to display per page", :onchange => 'this.form.submit()') %> per page
					<% end %>
    	    <%= search_as_hidden_fields(:omit_keys => [:page, :per_page]) %>
     			<noscript><%= submit_tag 'update' %></noscript>
    		<% end %>
    	<% end %>
    </div>
    <% unless params[:controller] == "folder" %>
  	  <%= render :partial=>'/catalog/document_actions' %>
  	<% end %>

    <div id="resultsRSS">
    	<% unless total < 1 or params[:controller] == "folder"  %>
			<% rss_params = params.dup %>
			<% rss_params.delete :controller %>
     	<%= link_to(
       image_tag('browser-rss.png', :alt => 'RSS feed', :title => 'RSS feed', :height => '20', :width => '20'),
       portal_index_path(:format => :rss) + "?" + rss_params.to_query, :target => '_blank', :id => "resultsRSSLink"
     )%>    
     <% end %>
    </div>

    <% unless params[:view]=='print' %>
      <%= link_to "Print View", params.merge(:view => :print), :class => 'printPreview', :target => 'blank', :title => "Print View" %>
    <% end %>

  </div>

<% end %>

app/views/catalog/endnote.endnote.erb
<%= render_endnote_texts(@documents) %>

app/views/catalog/status.json.erb
<%= @json_data %>